 {{- if .Values.PersistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" .}}-pvc
spec:
  accessModes:
  - {{.Values.PersistentVolumeClaim.accessMode}}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.size}}
  {{- end}}