{{- if .Values.PersistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.PersistentVolume.size}}  # Asegúrate de cambiar esto según tus necesidades
  accessModes:
    - {{ .Values.PersistentVolume.accessMode}}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/app/
{{- end}}