apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo-cd
  name: argocd-pipe
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "update"]
